spring :
  profiles :
    active : dev
  datasource :
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
    username : root
    password : root

session :
  http_only : false
  #设置为true 之后 cookie 只能在 HTTPS 连接中被浏览器传递到服务器端进行会话验证
  transferred_over_https_only : false
  # 过期时间
  expire_time_in_seconds : 86400

mybatis :
  type-aliases-package : com.neo.entity


server:
    port: 8080